method: "SPARSEGRPO"
model_path: 'finetune/2025-05-19_20-26-16/checkpoint-1647'
tokenizer_path:  'Salesforce/codet5p-220m'
max_new_length: 512
batch_size: 1
n_epochs: 5

num_return_sequences: 8

training_curriculum_config:
  type: BaselineCurriculum
  params:
    dir_paths: [ data/training]
    

evaluation_curriculum_config:
  type: BaselineCurriculum
  params:
    is_eval: True


env_config:
  type: LineLevelArcEnv
  params:
    tokenizer_path: 'Salesforce/codet5p-220m'
    n_examples:  10
    max_task_len: 256
    max_state_len: 256
    n_actions:  5
    token_budget:  500
